# Generated by Django 5.2.13 on 2026-04-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discountPercentage', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.URLField(blank=True, max_length=1200)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'price'], name='products_pr_categor_ad7451_idx'), models.Index(fields=['category', 'rating'], name='products_pr_categor_5c4a6b_idx'), models.Index(fields=['price', 'rating'], name='products_pr_price_bb796d_idx')],
            },
        ),
    ]
