# Generated by Django 5.2.13 on 2026-04-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_ad7451_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_5c4a6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_price_bb796d_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
