# Generated by Django 5.1.5 on 2025-06-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('SSLCOMMERZ', 'SSLCOMMERZ'), ('COD', 'Cash on Delivery')], default='COD', max_length=20),
        ),
    ]
