# Generated by Django 5.1.5 on 2025-06-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
